INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Advogado','book-open-blank-variant', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Arquiteto','pencil', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Artista','palette', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Ator','drama-masks', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Babá','baby-carriage', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Barman','beer', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Cabeleireiro','hair-dryer', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Carpinteiro','hand-saw', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Contador','calculator-variant', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Cozinheiro','chef-hat', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Cuidador','human-wheelchair', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Dentista','tooth-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Desenvolvedor','code-tags', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Design Gráfico','vector-circle', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Doméstica','broom', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Economista','attach-money', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Editor de Textos','text-box-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Editor de Vídeo','film', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Eletricista','lightning-bolt-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Enfermeira','medical-bag', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Engenheiro','tools', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Entregador','motorbike', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Esteticista','bow-tie', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Farmacêutico','pill', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Fisioterapeuta','yoga', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Fotógrafo','camera-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Garçom','silverware-fork-knife', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Investigador','glasses', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Jardineiro','flower-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Mecânico','wrench-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Médico','doctor', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Motorista','car-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Músico','music-note', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Nutricionista','food-apple-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Padeiro','bread-slice', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Pedreiro','greenhouse', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Personal Trainer','jump-rope', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Pintor','format-paint', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Professor','school-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Psicólogo','brain', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Secretária','account-tie', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Social Media','instagram', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Soldador','fire', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Taxista','taxi', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Técnico de TI','laptop', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Técnico em Segurança do Trabalho','shoe-cleat', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Tradutor','translate', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Vendedor','cash-register', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Veterinário','dog-service', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Encanador','pipe-wrench', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Engenheiro','math-compass', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Manicure','hand-back-right-outline', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Designer de Moda','bow-tie', TRUE, FALSE);
INSERT INTO allo.profissao (nome, nome_icone, ativo, suggestion) VALUES ('Costureiro','tshirt-crew-outline', TRUE, FALSE);
